services:

  postgres:
    image: postgres:14 
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: auth_admin
    volumes:
      - ./db/postgres/tmp/db:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    # hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: todo_admin
      MYSQL_PASSWORD: todo_admin
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  auth-service:
    build:
      context: .
      dockerfile: ./authService/authService.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres

  todo-service:
    build:
      context: .
      dockerfile: ./todoService/todoService.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - mysql
      - auth-service

  gateway-service:
    build:
      context: .
      dockerfile: ./gatewayService/gatewayService.dockerfile
    restart: always
    ports:
      - "8190:8190"
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - auth-service
      - todo-service
      - mysql
      
  redis:
    hostname: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379