CREATE USER todo_admin WITH PASSWORD '123456789' CREATEDB;

CREATE DATABASE todo WITH OWNER = todo_admin ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8' TABLESPACE = pg_default CONNECTION
LIMIT
    = -1;

GRANT ALL PRIVILEGES ON DATABASE todo TO todo_admin;